### ISSUE TITLE
super walls

### ISSUE THREAD

**Issue by yanasena** [rplcnn/SuperWalls#1]
6:33:59 PM [ERROR] The server has stopped responding!
6:33:59 PM [ERROR] Please report this to http://www.spigotmc.org/
6:33:59 PM [ERROR] Be sure to include ALL relevant console errors and Minecraft crash reports
6:33:59 PM [ERROR] Spigot version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
6:33:59 PM [ERROR] ------------------------------
6:33:59 PM [ERROR] Server thread dump (Look for plugins here before reporting to Spigot!):
6:33:59 PM [ERROR] ------------------------------
6:33:59 PM [ERROR] Current Thread: Server thread
6:33:59 PM [ERROR]  PID: 14 | Suspended: false | Native: false | State: WAITING
6:33:59 PM [ERROR]  Stack:
6:33:59 PM [ERROR]      sun.misc.Unsafe.park(Native Method)
6:33:59 PM [ERROR]      java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
6:33:59 PM [ERROR]      java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
6:34:00 PM [ERROR]      java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
6:34:00 PM [ERROR]      java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
6:34:00 PM [ERROR]      java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:945)
6:34:00 PM [ERROR]      ch.njol.skript.variables.Variables.setVariable(Variables.java:274)
6:34:00 PM [ERROR]      ch.njol.skript.variables.Variables.setVariable(Variables.java:268)
6:34:00 PM [ERROR]      ch.njol.skript.lang.Variable.set(Variable.java:318)
6:34:00 PM [ERROR]      ch.njol.skript.lang.Variable.change(Variable.java:362)
6:34:00 PM [ERROR]      ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
6:34:00 PM [ERROR]      ch.njol.skript.lang.Effect.run(Effect.java:50)
6:34:00 PM [ERROR]      ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
6:34:00 PM [ERROR]      ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
6:34:00 PM [ERROR]      ch.njol.skript.effects.Delay$1.run(Delay.java:85)
6:34:00 PM [ERROR]      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
6:34:00 PM [ERROR]      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
6:34:00 PM [ERROR]      java.lang.Thread.run(Thread.java:745)
6:34:00 PM [ERROR] ------------------------------
6:34:00 PM [ERROR] Entire Thread Dump:
6:34:00 PM [ERROR] ------------------------------
6:34:00 PM [ERROR] Current Thread: Craft Scheduler Thread - 10
6:34:00 PM [ERROR]  PID: 82 | Suspended: false | Native: false | State: RUNNABLE
6:34:00 PM [ERROR]  Thread is waiting on monitor(s):
6:34:00 PM [ERROR]      Locked on:java.lang.Throwable.fillInStackTrace(Throwable.java:783)
6:34:00 PM [ERROR]      Locked on:ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:379)
6:34:00 PM [ERROR]  Stack:
6:34:00 PM [ERROR]      java.lang.Throwable.fillInStackTrace(Native Method)
6:34:00 PM [ERROR]      java.lang.Throwable.fillInStackTrace(Throwable.java:783)
6:34:00 PM [ERROR]      java.lang.Throwable.<init>(Throwable.java:265)
6:34:00 PM [ERROR]      java.lang.Exception.<init>(Exception.java:66)
6:34:00 PM [ERROR]      java.io.IOException.<init>(IOException.java:58)
6:34:00 PM [ERROR]      java.io.ObjectStreamException.<init>(ObjectStreamException.java:44)
6:34:00 PM [ERROR]      java.io.StreamCorruptedException.<init>(StreamCorruptedException.java:45)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.Fields.getObject(Fields.java:325)
6:34:00 PM [ERROR]      ch.njol.skript.classes.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:61)
6:34:00 PM [ERROR]      ch.njol.skript.classes.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:1)
6:34:00 PM [ERROR]      ch.njol.skript.classes.Serializer.deserialize(Serializer.java:126)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:332)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.Yggdrasil.getID(Yggdrasil.java:214)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:192)
6:34:00 PM [ERROR]      ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
6:34:00 PM [ERROR]      ch.njol.skript.registrations.Classes.serialize(Classes.java:681)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:423)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:416)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:416)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:416)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:416)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:379)
6:34:00 PM [ERROR]      ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:200)
6:34:00 PM [ERROR]      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
6:34:00 PM [ERROR]      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
6:34:00 PM [ERROR]      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
6:34:00 PM [ERROR]      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
6:34:00 PM [ERROR]      java.lang.Thread.run(Thread.java:745)
6:34:00 PM [ERROR] ------------------------------
6:34:00 PM [ERROR] Current Thread: File IO Thread
6:34:00 PM [ERROR]  PID: 49 | Suspended: false | Native: false | State: TIMED_WAITING
6:34:00 PM [ERROR]  Stack:
6:34:00 PM [ERROR]      java.lang.Thread.sleep(Native Method)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:52)
6:34:00 PM [ERROR]      net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28)
6:34:00 PM [ERROR]      java.lang.Thread.run(Thread.java:745)
6:34:00 PM [ERROR] ------------------------------
6:34:00 PM [ERROR] Current Thread: Chunk I/O Executor Thread-1
6:34:00 PM [ERROR]  PID: 48 | Suspended: false | Native: false | State: WAITING
6:34:00 PM [ERROR]  Stack:
6:34:00 PM [ERROR]      sun.misc.Unsafe.park(Native Method)
6:34:00 PM [ERROR]      java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
6:34:00 PM [ERROR]      java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
6:34:00 PM [ERROR]      java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6:34:00 PM [ERROR]      java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
6:34:00 PM [ERROR]      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
6:34:00 PM [ERROR]      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
6:34:00 PM [ERROR]      java.lang.Thread.run(Thread.java:745)
6:34:00 PM [ERROR] ------------------------------
6:34:00 PM [ERROR] Current Thread: Skript variable save thread
6:34:00 PM [ERROR]  PID: 34 | Suspended: false | Native: false | State: WAITING
6:34:00 PM [ERROR]  Stack:
6:34:00 PM [ERROR]      sun.misc.Unsafe.park(Native Method)
6:34:00 PM [ERROR]      java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
6:34:00 PM [ERROR]      java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
6:34:00 PM [ERROR]      java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6:34:00 PM [ERROR]      ch.njol.skript.variables.Variables$2.run(Variables.java:378)

**Comment by rplcnn** [comment]
will be fixed
